Deck.create(name: 'No deck listed')

# # Closed Alpha Tournaments
# atl = Player.create(ign: 'Atlanta' )
# ben = Player.create(name: 'Ben Sullivan', ign: 'BeneBeats' )
# bmc = Player.create(ign: 'bmcfluff' )
# connor = Player.create(ign: 'Connor' )
# dan = Player.create(ign: 'DanGing' )
# eot = Player.create(ign: 'EmperorOTide' )
# agenda = Player.create(ign: 'EpicAgenda' )
# cat = Player.create(ign: 'EPICat' )
# krok = Player.create(ign: 'Krokmaster' )
# liv = Player.create(ign: 'livious' )
# mag = Player.create(ign: 'Magnetic' )
# nhb = Player.create(ign: 'nhblandin' )
# nov = Player.create(name: 'Nathan Overbay', ign: 'noverb' )
# tat = Player.create(ign: 'TatDaddy' )
# tom = Player.create(ign: 'TomEpicGamin' )
# www = Player.create(ign: 'www' )
# ham = Player.create(ign: 'Hampuse1' )
#
# mag_reg = Registration.create(player_id: mag.id) # Magnetic
# tom_reg = Registration.create(player_id: tom.id) # TomEpicGamin
# atl_reg = Registration.create(player_id: atl.id) # Atlanta
# tat_reg = Registration.create(player_id: tat.id) # TatDaddy
# bmc_reg = Registration.create(player_id: bmc.id) # bmcfluff
# nhb_reg = Registration.create(player_id: nhb.id) # nhblandin
# nov_reg = Registration.create(player_id: nov.id) # noverb
# liv_reg = Registration.create(player_id: liv.id) # livious
# Match.create(tournament_id: t1.id, winner: mag_reg, loser: tom_reg, round: '1')
# Match.create(tournament_id: t1.id, winner: atl_reg, loser: tat_reg, round: '1')
# Match.create(tournament_id: t1.id, winner: bmc_reg, loser: nhb_reg, round: '1')
# Match.create(tournament_id: t1.id, winner: nov_reg, loser: liv_reg, round: '1')
# Match.create(tournament_id: t1.id, winner: nhb_reg, loser: tom_reg, round: '2')
# Match.create(tournament_id: t1.id, winner: mag_reg, loser: atl_reg, round: '2')
# Match.create(tournament_id: t1.id, winner: bmc_reg, loser: nov_reg, round: '2')
# Match.create(tournament_id: t1.id, winner: tat_reg, loser: liv_reg, round: '2')
# Match.create(tournament_id: t1.id, winner: liv_reg, loser: tom_reg, round: '3')
# Match.create(tournament_id: t1.id, winner: mag_reg, loser: bmc_reg, round: '3')
# Match.create(tournament_id: t1.id, winner: nhb_reg, loser: atl_reg, round: '3')
# Match.create(tournament_id: t1.id, winner: nov_reg, loser: tat_reg, round: '3')
#
# t2 = Tournament.create(name: 'June 2019 Monthly Digital', format: 'Dark Draft', date: DateTime.new(2019, 6, 29))
# tat_reg = Registration.create(player_id: tat.id)
# liv_reg = Registration.create(player_id: liv.id)
# eot_reg = Registration.create(player_id: eot.id)
# dan_reg = Registration.create(player_id: dan.id)
# atl_reg = Registration.create(player_id: atl.id)
# tom_reg = Registration.create(player_id: tom.id)
# mag_reg = Registration.create(player_id: mag.id)
# nov_reg = Registration.create(player_id: nov.id)
# Match.create(tournament_id: t2.id, winner: tat_reg, loser: liv_reg, round: '1')
# Match.create(tournament_id: t2.id, winner: eot_reg, loser: dan_reg, round: '1')
# Match.create(tournament_id: t2.id, winner: atl_reg, loser: tom_reg, round: '1')
# Match.create(tournament_id: t2.id, winner: mag_reg, loser: nov_reg, round: '1')
# Match.create(tournament_id: t2.id, winner: liv_reg, loser: nov_reg, round: '2')
# Match.create(tournament_id: t2.id, winner: dan_reg, loser: tom_reg, round: '2')
# Match.create(tournament_id: t2.id, winner: tat_reg, loser: atl_reg, round: '2')
# Match.create(tournament_id: t2.id, winner: eot_reg, loser: mag_reg, round: '2')
# Match.create(tournament_id: t2.id, winner: dan_reg, loser: mag_reg, round: '3')
# Match.create(tournament_id: t2.id, winner: tat_reg, loser: eot_reg, round: '3')
# Match.create(tournament_id: t2.id, winner: tom_reg, loser: nov_reg, round: '3')
# Match.create(tournament_id: t2.id, winner: liv_reg, loser: atl_reg, round: '3')
# Match.create(tournament_id: t2.id, winner: tat_reg, loser: liv_reg, round: 'finals')
#
# t3 = Tournament.create(name: 'July 2019 Monthly Digital', format: 'Dark Draft', date: DateTime.new(2019, 7, 27))
# tom_reg = Registration.create(player_id: tom.id)
# liv_reg = Registration.create(player_id: liv.id)
# ben_reg = Registration.create(player_id: ben.id)
# www_reg = Registration.create(player_id: www.id)
# ham_reg = Registration.create(player_id: ham.id)
# nov_reg = Registration.create(player_id: nov.id)
# connor_reg = Registration.create(player_id: connor.id)
# atl_reg = Registration.create(player_id: atl.id)
# mag_reg = Registration.create(player_id: mag.id)
# agenda_reg = Registration.create(player_id: agenda.id)
# bmc_reg = Registration.create(player_id: bmc.id)
# Match.create(tournament_id: t3.id, winner: tom_reg, loser: liv_reg, round: '1')
# Match.create(tournament_id: t3.id, winner: ben_reg, loser: www_reg, round: '1')
# Match.create(tournament_id: t3.id, winner: ham_reg, loser: nov_reg, round: '1')
# Match.create(tournament_id: t3.id, winner: connor_reg, loser: atl_reg, round: '1')
# Match.create(tournament_id: t3.id, winner: mag_reg, loser: agenda_reg, round: '1')
# Match.create(tournament_id: t3.id, winner: bmc_reg, loser: tom_reg, round: '2')
# Match.create(tournament_id: t3.id, winner: ben_reg, loser: mag_reg, round: '2')
# Match.create(tournament_id: t3.id, winner: www_reg, loser: nov_reg, round: '2')
# Match.create(tournament_id: t3.id, winner: agenda_reg, loser: atl_reg, round: '2')
# Match.create(tournament_id: t3.id, winner: liv_reg, loser: www_reg, round: '3')
# Match.create(tournament_id: t3.id, winner: agenda_reg, loser: ham_reg, round: '3')
# Match.create(tournament_id: t3.id, winner: mag_reg, loser: tom_reg, round: '3')
# Match.create(tournament_id: t3.id, winner: bmc_reg, loser: ben_reg, round: '3')
# Match.create(tournament_id: t3.id, winner: nov_reg, loser: connor_reg, round: '3')
# Match.create(tournament_id: t3.id, winner: mag_reg, loser: liv_reg, round: '4')
# Match.create(tournament_id: t3.id, winner: connor_reg, loser: www_reg, round: '4')
# Match.create(tournament_id: t3.id, winner: nov_reg, loser: tom_reg, round: '4')
# Match.create(tournament_id: t3.id, winner: ham_reg, loser: ben_reg, round: '4')
# Match.create(tournament_id: t3.id, winner: bmc_reg, loser: agenda_reg, round: '4')
# Match.create(tournament_id: t3.id, winner: ben_reg, loser: bmc_reg, round: 'semifinals')
# Match.create(tournament_id: t3.id, winner: ham_reg, loser: mag_reg, round: 'semifinals')
# Match.create(tournament_id: t3.id, winner: ben_reg, loser: ham_reg, round: 'finals')
#
# t4 = Tournament.create(name: 'August 2019 Monthly Digital', format: 'Constructed', date: DateTime.new(2019, 8, 31))
# tat_reg = Registration.create(player_id: tat.id)
# cat_reg = Registration.create(player_id: cat.id)
# dan_reg = Registration.create(player_id: dan.id)
# mag_reg = Registration.create(player_id: mag.id)
# nov_reg = Registration.create(player_id: nov.id)
# atl_reg = Registration.create(player_id: atl.id)
# Match.create(tournament_id: t4.id, winner: tat_reg, loser: cat_reg, round: '1')
# Match.create(tournament_id: t4.id, winner: atl_reg, loser: dan_reg, round: '1')
# Match.create(tournament_id: t4.id, winner: mag_reg, loser: nov_reg, round: '1')
# Match.create(tournament_id: t4.id, winner: mag_reg, loser: atl_reg, round: '2')
# Match.create(tournament_id: t4.id, winner: tat_reg, loser: dan_reg, round: '2')
# Match.create(tournament_id: t4.id, winner: cat_reg, loser: nov_reg, round: '2')
# Match.create(tournament_id: t4.id, winner: atl_reg, loser: cat_reg, round: '3')
# Match.create(tournament_id: t4.id, winner: nov_reg, loser: dan_reg, round: '3')
# Match.create(tournament_id: t4.id, winner: mag_reg, loser: tat_reg, round: '3')
# Match.create(tournament_id: t4.id, winner: tat_reg, loser: mag_reg, round: 'finals')
#
# Tournament.create(name: 'September 2019 Monthly Digital', format: 'Dark Draft', date: DateTime.new(2019, 9, 28))


luc = Player.create(ign: 'HLuca')
mox = Player.create(ign: 'Moxlessmatt')
ben = Player.create(name: 'Ben Sullivan', ign: 'BeneBeats')
ham = Player.create(ign: 'Hampuse1')
nat = Player.create(ign: 'noverb')
tat = Player.create(ign: 'TatDaddy')
bmc = Player.create(ign: 'bmcfluff')
mag = Player.create(ign: 'Magnetic')
nhb = Player.create(ign: 'NHBlandin')
atl = Player.create(ign: 'Atlanta')
tom = Player.create(ign: 'TomEpicGamin')
epi = Player.create(ign: 'EpicAgenda')

t1 = Tournament.create(name: 'February 2020 Monthly Digital', format: 'Dark Draft', date: DateTime.new(2020, 2, 29))

luc_reg = Registration.create(player_id: luc.id)
mox_reg = Registration.create(player_id: mox.id)
ben_reg = Registration.create(player_id: ben.id)
ham_reg = Registration.create(player_id: ham.id)
nat_reg = Registration.create(player_id: nat.id)
tat_reg = Registration.create(player_id: tat.id)
bmc_reg = Registration.create(player_id: bmc.id)
mag_reg = Registration.create(player_id: mag.id)
nhb_reg = Registration.create(player_id: nhb.id)
atl_reg = Registration.create(player_id: atl.id)
tom_reg = Registration.create(player_id: tom.id)
epi_reg = Registration.create(player_id: epi.id)

# February Round 1
Match.create(tournament_id: t1.id, winner: luc_reg, loser: mox_reg, round: '1')
Match.create(tournament_id: t1.id, winner: ben_reg, loser: ham_reg, round: '1')
Match.create(tournament_id: t1.id, winner: tat_reg, loser: nat_reg, round: '1')
Match.create(tournament_id: t1.id, winner: bmc_reg, loser: mag_reg, round: '1')
Match.create(tournament_id: t1.id, winner: atl_reg, loser: nhb_reg, round: '1')
Match.create(tournament_id: t1.id, winner: tom_reg, loser: epi_reg, round: '1')
# February Round 2
Match.create(tournament_id: t1.id, winner: tat_reg, loser: atl_reg, round: '2')
Match.create(tournament_id: t1.id, winner: ben_reg, loser: bmc_reg, round: '2')
Match.create(tournament_id: t1.id, winner: tom_reg, loser: luc_reg, round: '2')
Match.create(tournament_id: t1.id, winner: nhb_reg, loser: mox_reg, round: '2')
Match.create(tournament_id: t1.id, winner: mag_reg, loser: nat_reg, round: '2')
Match.create(tournament_id: t1.id, winner: ham_reg, loser: epi_reg, round: '2')
# February Round 3
Match.create(tournament_id: t1.id, winner: ham_reg, loser: bmc_reg, round: '3')
Match.create(tournament_id: t1.id, winner: mag_reg, loser: nhb_reg, round: '3')
Match.create(tournament_id: t1.id, winner: epi_reg, loser: luc_reg, round: '3')
Match.create(tournament_id: t1.id, winner: nat_reg, loser: mox_reg, round: '3')
Match.create(tournament_id: t1.id, winner: tat_reg, loser: ben_reg, round: '3')
Match.create(tournament_id: t1.id, winner: tom_reg, loser: atl_reg, round: '3')
# February Round 4
Match.create(tournament_id: t1.id, winner: tom_reg, loser: tat_reg, round: '4')
Match.create(tournament_id: t1.id, winner: mag_reg, loser: ben_reg, round: '4')
Match.create(tournament_id: t1.id, winner: atl_reg, loser: ham_reg, round: '4')
Match.create(tournament_id: t1.id, winner: bmc_reg, loser: nhb_reg, round: '4')
Match.create(tournament_id: t1.id, winner: epi_reg, loser: mox_reg, round: '4')
Match.create(tournament_id: t1.id, winner: luc_reg, loser: nat_reg, round: '4')
# February Semifinals
semi = 'semifinals'
Match.create(tournament_id: t1.id, winner: tom_reg, loser: atl_reg, round: semi)
Match.create(tournament_id: t1.id, winner: tat_reg, loser: mag_reg, round: semi)
# February Finals
Match.create(tournament_id: t1.id, winner: tat_reg, loser: tom_reg, round: 'finals')

# March New Players
ped = Player.create(ign: 'Pedro')
kro = Player.create(ign: 'Krokmaster')
sir = Player.create(ign: 'Sir3')
por = Player.create(ign: 'Porkylorky')
cat = Player.create(ign: 'EPICat')
www = Player.create(ign: 'www')
gyp = Player.create(ign: 'GeneralGyp')
oak = Player.create(ign: 'OakenShield')

# March Registrations
tom_reg = Registration.create(player_id: tom.id)
ben_reg = Registration.create(player_id: ben.id)
mag_reg = Registration.create(player_id: mag.id)
ham_reg = Registration.create(player_id: ham.id)
atl_reg = Registration.create(player_id: atl.id)
tat_reg = Registration.create(player_id: tat.id)
ped_reg = Registration.create(player_id: ped.id)
kro_reg = Registration.create(player_id: kro.id)
sir_reg = Registration.create(player_id: sir.id)
por_reg = Registration.create(player_id: por.id)
cat_reg = Registration.create(player_id: cat.id)
www_reg = Registration.create(player_id: www.id)
gyp_reg = Registration.create(player_id: gyp.id)
oak_reg = Registration.create(player_id: oak.id)

# March Tournament
t2 = Tournament.create(name: 'March 2020 Monthly Digital', format: 'Constructed', date: DateTime.new(2020, 3, 28))

# March Round 1
Match.create(tournament_id: t2.id, winner: tom_reg, loser: ped_reg, round: '1')
Match.create(tournament_id: t2.id, winner: ben_reg, loser: kro_reg, round: '1')
Match.create(tournament_id: t2.id, winner: sir_reg, loser: mag_reg, round: '1')
Match.create(tournament_id: t2.id, winner: ham_reg, loser: por_reg, round: '1')
Match.create(tournament_id: t2.id, winner: www_reg, loser: cat_reg, round: '1')
Match.create(tournament_id: t2.id, winner: atl_reg, loser: gyp_reg, round: '1')
Match.create(tournament_id: t2.id, winner: tat_reg, loser: oak_reg, round: '1')
# March Round 2
Match.create(tournament_id: t2.id, winner: tom_reg, loser: www_reg, round: '2')
Match.create(tournament_id: t2.id, winner: tat_reg, loser: sir_reg, round: '2')
Match.create(tournament_id: t2.id, winner: atl_reg, loser: ben_reg, round: '2')
Match.create(tournament_id: t2.id, winner: ped_reg, loser: ham_reg, round: '2')
Match.create(tournament_id: t2.id, winner: mag_reg, loser: oak_reg, round: '2')
Match.create(tournament_id: t2.id, winner: cat_reg, loser: kro_reg, round: '2')
Match.create(tournament_id: t2.id, winner: por_reg, loser: gyp_reg, round: '2')
# March Round 3
Match.create(tournament_id: t2.id, winner: atl_reg, loser: tom_reg, round: '3')
Match.create(tournament_id: t2.id, winner: www_reg, loser: tat_reg, round: '3')
Match.create(tournament_id: t2.id, winner: ped_reg, loser: sir_reg, round: '3')
Match.create(tournament_id: t2.id, winner: ben_reg, loser: ham_reg, round: '3')
Match.create(tournament_id: t2.id, winner: mag_reg, loser: cat_reg, round: '3')
Match.create(tournament_id: t2.id, winner: oak_reg, loser: por_reg, round: '3')
Match.create(tournament_id: t2.id, winner: gyp_reg, loser: kro_reg, round: '3')
# March Round 4
Match.create(tournament_id: t2.id, winner: www_reg, loser: atl_reg, round: '4')
Match.create(tournament_id: t2.id, winner: tom_reg, loser: ben_reg, round: '4')
Match.create(tournament_id: t2.id, winner: tat_reg, loser: ped_reg, round: '4')
Match.create(tournament_id: t2.id, winner: ham_reg, loser: mag_reg, round: '4')
Match.create(tournament_id: t2.id, winner: oak_reg, loser: sir_reg, round: '4')
Match.create(tournament_id: t2.id, winner: gyp_reg, loser: cat_reg, round: '4')
Match.create(tournament_id: t2.id, winner: por_reg, loser: kro_reg, round: '4')
# March Semifinals
Match.create(tournament_id: t2.id, winner: tat_reg, loser: atl_reg, round: 'semifinals')
Match.create(tournament_id: t2.id, winner: tom_reg, loser: www_reg, round: 'semifinals')
# March Finals
Match.create(tournament_id: t2.id, winner: tom_reg, loser: tat_reg, round: 'finals')

# April New Players
esc = Player.create(ign: 'escopeta666')
jaz = Player.create(ign: 'jazzbjorn')
avi = Player.create(ign: 'Avian')
emp = Player.create(ign: 'EmperorOTide')
tat = Player.create(ign: 'Tatian')
was = Player.create(ign: 'Wasabi')

# April Tournament
t3 = Tournament.create(name: 'April 2020 Monthly Digital', format: 'Dark Draft', date: DateTime.new(2020, 4, 25))

# April Registrations
esc_reg = Registration.create(player_id: esc.id)
por_reg = Registration.create(player_id: por.id)
jaz_reg = Registration.create(player_id: jaz.id)
avi_reg = Registration.create(player_id: avi.id)
ham_reg = Registration.create(player_id: ham.id)
sir_reg = Registration.create(player_id: sir.id)
mag_reg = Registration.create(player_id: mag.id)
emp_reg = Registration.create(player_id: emp.id)
tom_reg = Registration.create(player_id: tom.id)
tat_reg = Registration.create(player_id: tat.id)
atl_reg = Registration.create(player_id: atl.id)
was_reg = Registration.create(player_id: was.id)
bmc_reg = Registration.create(player_id: bmc.id)
epi_reg = Registration.create(player_id: epi.id)

# April Round 1
Match.create(tournament_id: t3.id, winner: por_reg, loser: esc_reg, round: '1')
Match.create(tournament_id: t3.id, winner: avi_reg, loser: jaz_reg, round: '1')
Match.create(tournament_id: t3.id, winner: sir_reg, loser: ham_reg, round: '1')
Match.create(tournament_id: t3.id, winner: mag_reg, loser: emp_reg, round: '1')
Match.create(tournament_id: t3.id, winner: epi_reg, loser: tom_reg, round: '1')
Match.create(tournament_id: t3.id, winner: atl_reg, loser: tat_reg, round: '1')
Match.create(tournament_id: t3.id, winner: was_reg, loser: bmc_reg, round: '1')
# April Round 2
Match.create(tournament_id: t3.id, winner: epi_reg, loser: atl_reg, round: '2')
Match.create(tournament_id: t3.id, winner: por_reg, loser: sir_reg, round: '2')
Match.create(tournament_id: t3.id, winner: avi_reg, loser: was_reg, round: '2')
Match.create(tournament_id: t3.id, winner: mag_reg, loser: esc_reg, round: '2')
Match.create(tournament_id: t3.id, winner: jaz_reg, loser: ham_reg, round: '2')
Match.create(tournament_id: t3.id, winner: tat_reg, loser: tom_reg, round: '2')
Match.create(tournament_id: t3.id, winner: bmc_reg, loser: emp_reg, round: '2')
# April Round 3
Match.create(tournament_id: t3.id, winner: avi_reg, loser: epi_reg, round: '3')
Match.create(tournament_id: t3.id, winner: por_reg, loser: mag_reg, round: '3')
Match.create(tournament_id: t3.id, winner: atl_reg, loser: was_reg, round: '3')
Match.create(tournament_id: t3.id, winner: sir_reg, loser: jaz_reg, round: '3')
Match.create(tournament_id: t3.id, winner: tat_reg, loser: bmc_reg, round: '3')
Match.create(tournament_id: t3.id, winner: tom_reg, loser: esc_reg, round: '3')
Match.create(tournament_id: t3.id, winner: ham_reg, loser: emp_reg, round: '3')
# April Round 4
Match.create(tournament_id: t3.id, winner: por_reg, loser: avi_reg, round: '4')
Match.create(tournament_id: t3.id, winner: sir_reg, loser: epi_reg, round: '4')
Match.create(tournament_id: t3.id, winner: mag_reg, loser: atl_reg, round: '4')
Match.create(tournament_id: t3.id, winner: tat_reg, loser: jaz_reg, round: '4')
Match.create(tournament_id: t3.id, winner: was_reg, loser: tom_reg, round: '4')
Match.create(tournament_id: t3.id, winner: ham_reg, loser: bmc_reg, round: '4')
Match.create(tournament_id: t3.id, winner: esc_reg, loser: emp_reg, round: '4')
# April Semifinals
Match.create(tournament_id: t3.id, winner: mag_reg, loser: por_reg, round: 'semifinals')
Match.create(tournament_id: t3.id, winner: sir_reg, loser: avi_reg, round: 'semifinals')
# April Finals
Match.create(tournament_id: t3.id, winner: mag_reg, loser: sir_reg, round: 'finals')

# May Tournament
t4 = Tournament.create(name: 'May 2020 Monthly Digital', format: 'Constructed', date: DateTime.new(2020, 5, 30))

# May New Players
dre = Player.create(ign: 'Drewise1')
bet = Player.create(ign: 'bethzur')
liv = Player.create(ign: 'livious')

# May Registrations
ben_reg = Registration.create(player_id: ben.id)
epi_reg = Registration.create(player_id: epi.id)
avi_reg = Registration.create(player_id: avi.id)
mag_reg = Registration.create(player_id: mag.id)
dre_reg = Registration.create(player_id: dre.id)
tat_reg = Registration.create(player_id: tat.id)
liv_reg = Registration.create(player_id: liv.id)
tom_reg = Registration.create(player_id: tom.id)
ham_reg = Registration.create(player_id: ham.id)
bet_reg = Registration.create(player_id: bet.id)
atl_reg = Registration.create(player_id: atl.id)
nat_reg = Registration.create(player_id: nat.id)

# May Round 1
Match.create(tournament_id: t4.id, winner: ben_reg, loser: epi_reg, round: '1')
Match.create(tournament_id: t4.id, winner: mag_reg, loser: avi_reg, round: '1')
Match.create(tournament_id: t4.id, winner: dre_reg, loser: tat_reg, round: '1')
Match.create(tournament_id: t4.id, winner: liv_reg, loser: tom_reg, round: '1')
Match.create(tournament_id: t4.id, winner: ham_reg, loser: bet_reg, round: '1')
Match.create(tournament_id: t4.id, winner: nat_reg, loser: atl_reg, round: '1')
# May Round 2
Match.create(tournament_id: t4.id, winner: dre_reg, loser: ben_reg, round: '2')
Match.create(tournament_id: t4.id, winner: nat_reg, loser: mag_reg, round: '2')
Match.create(tournament_id: t4.id, winner: ham_reg, loser: liv_reg, round: '2')
Match.create(tournament_id: t4.id, winner: atl_reg, loser: tat_reg, round: '2')
Match.create(tournament_id: t4.id, winner: epi_reg, loser: bet_reg, round: '2')
Match.create(tournament_id: t4.id, winner: avi_reg, loser: tom_reg, round: '2')
# May Round 3
Match.create(tournament_id: t4.id, winner: nat_reg, loser: dre_reg, round: '3')
Match.create(tournament_id: t4.id, winner: ben_reg, loser: ham_reg, round: '3')
Match.create(tournament_id: t4.id, winner: atl_reg, loser: mag_reg, round: '3')
Match.create(tournament_id: t4.id, winner: epi_reg, loser: liv_reg, round: '3')
Match.create(tournament_id: t4.id, winner: avi_reg, loser: tat_reg, round: '3')
Match.create(tournament_id: t4.id, winner: tom_reg, loser: bet_reg, round: '3')
# May Round 4
Match.create(tournament_id: t4.id, winner: epi_reg, loser: ham_reg, round: '4')
Match.create(tournament_id: t4.id, winner: avi_reg, loser: liv_reg, round: '4')
Match.create(tournament_id: t4.id, winner: tom_reg, loser: mag_reg, round: '4')
Match.create(tournament_id: t4.id, winner: bet_reg, loser: tat_reg, round: '4')
Match.create(tournament_id: t4.id, winner: atl_reg, loser: dre_reg, round: '4')
Match.create(tournament_id: t4.id, winner: ben_reg, loser: nat_reg, round: '4')
# May Semifinals
Match.create(tournament_id: t4.id, winner: atl_reg, loser: ben_reg, round: 'semifinals')
Match.create(tournament_id: t4.id, winner: epi_reg, loser: nat_reg, round: 'semifinals')
# May Finals
Match.create(tournament_id: t4.id, winner: epi_reg, loser: atl_reg, round: 'finals')

# June Legend Series
t5 = Tournament.create(name: 'Legend Series', format: 'Dark Draft', date: DateTime.new(2020, 6, 19))

# Legend Series New Players
sug = Player.create(ign: 'SugarToes')
cla = Player.create(ign: 'Clarkasaur')
tex = Player.create(ign: 'thetexan')
inl = Player.create(ign: 'inline')
sim = Player.create(ign: 'simonlex')
m04 = Player.create(ign: 'Match04')
cir = Player.create(ign: 'Cireva')
glo = Player.create(ign: 'glotzer')
ads = Player.create(ign: 'AdSeaneam')
ret = Player.create(ign: 'RetroKC')
mat = Player.create(ign: 'Matney')
tcg = Player.create(ign: 'TCGcuthulhu')
gru = Player.create(ign: 'grumpypiggy')
cut = Player.create(ign: 'TheCutter')
owe = Player.create(ign: 'owenshen24')
fis = Player.create(ign: 'fish3r')
sta = Player.create(ign: 'Stag')
got = Player.create(ign: 'gottim')
con = Player.create(ign: 'Connor' )

# Legend Series Registrations
tex_reg = Registration.create(player_id: tex.id)
bmc_reg = Registration.create(player_id: bmc.id)
ben_reg = Registration.create(player_id: ben.id)
sug_reg = Registration.create(player_id: sug.id)
cla_reg = Registration.create(player_id: cla.id)
avi_reg = Registration.create(player_id: avi.id)
inl_reg = Registration.create(player_id: inl.id)
sim_reg = Registration.create(player_id: sim.id)
m04_reg = Registration.create(player_id: m04.id)
jaz_reg = Registration.create(player_id: jaz.id)
cir_reg = Registration.create(player_id: cir.id)
dre_reg = Registration.create(player_id: dre.id)
glo_reg = Registration.create(player_id: glo.id)
ads_reg = Registration.create(player_id: ads.id)
ret_reg = Registration.create(player_id: ret.id)
con_reg = Registration.create(player_id: con.id)
nat_reg = Registration.create(player_id: nat.id)
mox_reg = Registration.create(player_id: mox.id)
liv_reg = Registration.create(player_id: liv.id)
was_reg = Registration.create(player_id: was.id)
tcg_reg = Registration.create(player_id: tcg.id)
gru_reg = Registration.create(player_id: gru.id)
tom_reg = Registration.create(player_id: tom.id)
cut_reg = Registration.create(player_id: cut.id)
owe_reg = Registration.create(player_id: owe.id)
mat_reg = Registration.create(player_id: mat.id)
fis_reg = Registration.create(player_id: fis.id)
tat_reg = Registration.create(player_id: tat.id)
sta_reg = Registration.create(player_id: sta.id)
cat_reg = Registration.create(player_id: cat.id)
got_reg = Registration.create(player_id: got.id)

# Round 1
Match.create(tournament_id: t5.id, winner: bmc_reg, loser: ben_reg, round: '1')
Match.create(tournament_id: t5.id, winner: cla_reg, loser: sug_reg, round: '1')
Match.create(tournament_id: t5.id, winner: avi_reg, loser: tex_reg, round: '1')
Match.create(tournament_id: t5.id, winner: sim_reg, loser: inl_reg, round: '1')
Match.create(tournament_id: t5.id, winner: jaz_reg, loser: m04_reg, round: '1')
Match.create(tournament_id: t5.id, winner: cir_reg, loser: dre_reg, round: '1')
Match.create(tournament_id: t5.id, winner: ads_reg, loser: glo_reg, round: '1')
Match.create(tournament_id: t5.id, winner: ret_reg, loser: con_reg, round: '1')
Match.create(tournament_id: t5.id, winner: nat_reg, loser: mat_reg, round: '1')
Match.create(tournament_id: t5.id, winner: liv_reg, loser: was_reg, round: '1')
Match.create(tournament_id: t5.id, winner: tcg_reg, loser: gru_reg, round: '1')
Match.create(tournament_id: t5.id, winner: cut_reg, loser: tom_reg, round: '1')
Match.create(tournament_id: t5.id, winner: owe_reg, loser: mox_reg, round: '1')
Match.create(tournament_id: t5.id, winner: tat_reg, loser: fis_reg, round: '1')
Match.create(tournament_id: t5.id, winner: sta_reg, loser: epi_reg, round: '1')
# Match.create(tournament_id: t5.id, winner: got_reg, loser: BYE, round: '1')

# Round 2
Match.create(tournament_id: t5.id, winner: tat_reg, loser: avi_reg, round: '2')
Match.create(tournament_id: t5.id, winner: sta_reg, loser: cut_reg, round: '2')
Match.create(tournament_id: t5.id, winner: liv_reg, loser: tcg_reg, round: '2')
Match.create(tournament_id: t5.id, winner: owe_reg, loser: cla_reg, round: '2')
Match.create(tournament_id: t5.id, winner: ret_reg, loser: sim_reg, round: '2')
Match.create(tournament_id: t5.id, winner: jaz_reg, loser: nat_reg, round: '2')
Match.create(tournament_id: t5.id, winner: bmc_reg, loser: ads_reg, round: '2')
Match.create(tournament_id: t5.id, winner: cir_reg, loser: got_reg, round: '2')
Match.create(tournament_id: t5.id, winner: fis_reg, loser: sug_reg, round: '2')
Match.create(tournament_id: t5.id, winner: m04_reg, loser: glo_reg, round: '2')
Match.create(tournament_id: t5.id, winner: mox_reg, loser: inl_reg, round: '2')
Match.create(tournament_id: t5.id, winner: dre_reg, loser: tex_reg, round: '2')
Match.create(tournament_id: t5.id, winner: gru_reg, loser: mat_reg, round: '2')
Match.create(tournament_id: t5.id, winner: tom_reg, loser: epi_reg, round: '2')
Match.create(tournament_id: t5.id, winner: ben_reg, loser: was_reg, round: '2')
# Match.create(tournament_id: t5.id, winner: con_reg, loser: BYE, round: '1')

# Round 3
Match.create(tournament_id: t5.id, winner: tat_reg, loser: owe_reg, round: '3')
Match.create(tournament_id: t5.id, winner: cir_reg, loser: ret_reg, round: '3')
Match.create(tournament_id: t5.id, winner: bmc_reg, loser: jaz_reg, round: '3')
Match.create(tournament_id: t5.id, winner: liv_reg, loser: sta_reg, round: '3')
Match.create(tournament_id: t5.id, winner: cut_reg, loser: tcg_reg, round: '3')
Match.create(tournament_id: t5.id, winner: m04_reg, loser: mox_reg, round: '3')
Match.create(tournament_id: t5.id, winner: avi_reg, loser: dre_reg, round: '3')
Match.create(tournament_id: t5.id, winner: sim_reg, loser: cla_reg, round: '3')
Match.create(tournament_id: t5.id, winner: nat_reg, loser: ben_reg, round: '3')
Match.create(tournament_id: t5.id, winner: ads_reg, loser: fis_reg, round: '3')
Match.create(tournament_id: t5.id, winner: con_reg, loser: got_reg, round: '3')
Match.create(tournament_id: t5.id, winner: gru_reg, loser: tom_reg, round: '3')
Match.create(tournament_id: t5.id, winner: epi_reg, loser: was_reg, round: '3')
Match.create(tournament_id: t5.id, winner: glo_reg, loser: tex_reg, round: '3')
Match.create(tournament_id: t5.id, winner: mat_reg, loser: inl_reg, round: '3')
# Match.create(tournament_id: t5.id, winner: sug_reg, loser: BYE, round: '1')

# Round 4
Match.create(tournament_id: t5.id, winner: bmc_reg, loser: tat_reg, round: '4')
Match.create(tournament_id: t5.id, winner: cir_reg, loser: liv_reg, round: '4')
Match.create(tournament_id: t5.id, winner: ret_reg, loser: jaz_reg, round: '4')
Match.create(tournament_id: t5.id, winner: sta_reg, loser: owe_reg, round: '4')
Match.create(tournament_id: t5.id, winner: cut_reg, loser: ads_reg, round: '4')
Match.create(tournament_id: t5.id, winner: m04_reg, loser: nat_reg, round: '4')
Match.create(tournament_id: t5.id, winner: avi_reg, loser: gru_reg, round: '4')
Match.create(tournament_id: t5.id, winner: con_reg, loser: sim_reg, round: '4')
Match.create(tournament_id: t5.id, winner: fis_reg, loser: tcg_reg, round: '4')
Match.create(tournament_id: t5.id, winner: dre_reg, loser: ben_reg, round: '4')
Match.create(tournament_id: t5.id, winner: tom_reg, loser: cla_reg, round: '4')
Match.create(tournament_id: t5.id, winner: mox_reg, loser: got_reg, round: '4')
Match.create(tournament_id: t5.id, winner: glo_reg, loser: mat_reg, round: '4')
Match.create(tournament_id: t5.id, winner: epi_reg, loser: sug_reg, round: '4')
Match.create(tournament_id: t5.id, winner: tex_reg, loser: was_reg, round: '4')
# Match.create(tournament_id: t5.id, winner: inl_reg, loser: BYE, round: '1')

# Round 5
Match.create(tournament_id: t5.id, winner: bmc_reg, loser: liv_reg, round: '5')
Match.create(tournament_id: t5.id, winner: tat_reg, loser: ret_reg, round: '5')
Match.create(tournament_id: t5.id, winner: sta_reg, loser: cir_reg, round: '5')
Match.create(tournament_id: t5.id, winner: cut_reg, loser: m04_reg, round: '5')
Match.create(tournament_id: t5.id, winner: avi_reg, loser: con_reg, round: '5')
Match.create(tournament_id: t5.id, winner: jaz_reg, loser: ads_reg, round: '5')
Match.create(tournament_id: t5.id, winner: dre_reg, loser: owe_reg, round: '5')
Match.create(tournament_id: t5.id, winner: tom_reg, loser: sim_reg, round: '5')
Match.create(tournament_id: t5.id, winner: nat_reg, loser: gru_reg, round: '5')
Match.create(tournament_id: t5.id, winner: mox_reg, loser: fis_reg, round: '5')
Match.create(tournament_id: t5.id, winner: epi_reg, loser: glo_reg, round: '5')
Match.create(tournament_id: t5.id, winner: got_reg, loser: tcg_reg, round: '5')
Match.create(tournament_id: t5.id, winner: ben_reg, loser: cla_reg, round: '5')
Match.create(tournament_id: t5.id, winner: mat_reg, loser: tex_reg, round: '5')
Match.create(tournament_id: t5.id, winner: inl_reg, loser: sug_reg, round: '5')
# Match.create(tournament_id: t5.id, winner: was_reg, loser: BYE, round: '1')

# Quarterfinals
Match.create(tournament_id: t5.id, winner: bmc_reg, loser: jaz_reg, round: 'quarterfinals')
Match.create(tournament_id: t5.id, winner: tat_reg, loser: ret_reg, round: 'quarterfinals')
Match.create(tournament_id: t5.id, winner: sta_reg, loser: avi_reg, round: 'quarterfinals')
Match.create(tournament_id: t5.id, winner: cir_reg, loser: cut_reg, round: 'quarterfinals')

# Semifinals
Match.create(tournament_id: t5.id, winner: bmc_reg, loser: tat_reg, round: 'semifinals')
Match.create(tournament_id: t5.id, winner: cir_reg, loser: sta_reg, round: 'semifinals')

# Finals
Match.create(tournament_id: t5.id, winner: bmc_reg, loser: cir_reg, round: 'finals')

# June Tournament
t6 = Tournament.create(name: 'June 2020 Monthly Digital', format: 'Dark Draft', date: DateTime.new(2020, 6, 27))

# June New Players
spa = Player.create(ign: 'EpicSpain')

# June Registrations
jaz_reg = Registration.create(player_id: jaz.id)
tat_reg = Registration.create(player_id: tat.id)
bmc_reg = Registration.create(player_id: bmc.id)
mox_reg = Registration.create(player_id: mox.id)
tom_reg = Registration.create(player_id: tom.id)
ham_reg = Registration.create(player_id: ham.id)
m04_reg = Registration.create(player_id: m04.id)
spa_reg = Registration.create(player_id: spa.id)
ben_reg = Registration.create(player_id: ben.id)
liv_reg = Registration.create(player_id: liv.id)
con_reg = Registration.create(player_id: con.id)
ret_reg = Registration.create(player_id: ret.id)
mag_reg = Registration.create(player_id: mag.id)
avi_reg = Registration.create(player_id: avi.id)
atl_reg = Registration.create(player_id: atl.id)
cir_reg = Registration.create(player_id: cir.id)

# Round 1
Match.create(tournament_id: t6.id, winner: tat_reg, loser: jaz_reg, round: '1')
Match.create(tournament_id: t6.id, winner: bmc_reg, loser: mox_reg, round: '1')
Match.create(tournament_id: t6.id, winner: ham_reg, loser: tom_reg, round: '1')
Match.create(tournament_id: t6.id, winner: m04_reg, loser: spa_reg, round: '1')
Match.create(tournament_id: t6.id, winner: ben_reg, loser: liv_reg, round: '1')
Match.create(tournament_id: t6.id, winner: ret_reg, loser: con_reg, round: '1')
Match.create(tournament_id: t6.id, winner: avi_reg, loser: mag_reg, round: '1')
Match.create(tournament_id: t6.id, winner: atl_reg, loser: cir_reg, round: '1')

# Round 2
Match.create(tournament_id: t6.id, winner: ham_reg, loser: m04_reg, round: '2')
Match.create(tournament_id: t6.id, winner: bmc_reg, loser: atl_reg, round: '2')
Match.create(tournament_id: t6.id, winner: ret_reg, loser: avi_reg, round: '2')
Match.create(tournament_id: t6.id, winner: tat_reg, loser: ben_reg, round: '2')
Match.create(tournament_id: t6.id, winner: con_reg, loser: mag_reg, round: '2')
Match.create(tournament_id: t6.id, winner: liv_reg, loser: tom_reg, round: '2')
Match.create(tournament_id: t6.id, winner: spa_reg, loser: mox_reg, round: '2')
Match.create(tournament_id: t6.id, winner: cir_reg, loser: jaz_reg, round: '2')

# Round 3
Match.create(tournament_id: t6.id, winner: spa_reg, loser: con_reg, round: '3')
Match.create(tournament_id: t6.id, winner: liv_reg, loser: cir_reg, round: '3')
Match.create(tournament_id: t6.id, winner: mox_reg, loser: tom_reg, round: '3')
Match.create(tournament_id: t6.id, winner: mag_reg, loser: jaz_reg, round: '3')
Match.create(tournament_id: t6.id, winner: ret_reg, loser: ham_reg, round: '3')
Match.create(tournament_id: t6.id, winner: tat_reg, loser: bmc_reg, round: '3')
Match.create(tournament_id: t6.id, winner: atl_reg, loser: m04_reg, round: '3')
Match.create(tournament_id: t6.id, winner: ben_reg, loser: avi_reg, round: '3')

# Round 4
Match.create(tournament_id: t6.id, winner: ret_reg, loser: tat_reg, round: '4')
Match.create(tournament_id: t6.id, winner: ben_reg, loser: bmc_reg, round: '4')
Match.create(tournament_id: t6.id, winner: atl_reg, loser: ham_reg, round: '4')
Match.create(tournament_id: t6.id, winner: liv_reg, loser: spa_reg, round: '4')
Match.create(tournament_id: t6.id, winner: con_reg, loser: m04_reg, round: '4')
Match.create(tournament_id: t6.id, winner: cir_reg, loser: avi_reg, round: '4')
Match.create(tournament_id: t6.id, winner: mag_reg, loser: mox_reg, round: '4')
Match.create(tournament_id: t6.id, winner: jaz_reg, loser: tom_reg, round: '4')

# Semifinals
Match.create(tournament_id: t6.id, winner: ret_reg, loser: atl_reg, round: 'semifinals')
Match.create(tournament_id: t6.id, winner: tat_reg, loser: ben_reg, round: 'semifinals')

# Finals
Match.create(tournament_id: t6.id, winner: tat_reg, loser: ret_reg, round: 'finals')